/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 -T -t scene.gltf --shadows
Author: AdrianXY (https://sketchfab.com/adrianxy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shopping-cart-b96f896453b240ae804d0399f1faf027
Title: Shopping Cart
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
    Griff: THREE.MeshStandardMaterial
    Chrome: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.material} scale={6.489} />
      <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials.Griff} scale={6.489} />
      <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials.Chrome} scale={6.489} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
