/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 -T -t scene.gltf --shadows
Author: silviaas (https://sketchfab.com/silviaas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pisa-tower-fccc1f388bdd40d5958f3d88c6de036a
Title: Pisa tower
*/

import * as THREE from "three";
import React, { forwardRef, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { GroupProps } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    TopFloor001_0: THREE.Mesh;
  };
  materials: {
    ["Scene_-_Root"]: THREE.MeshStandardMaterial;
  };
};

export const PisaTower = forwardRef<THREE.Group, GroupProps>(
  (props: JSX.IntrinsicElements["group"], ref) => {
    const { nodes, materials } = useGLTF(
      "/models/pisa_tower/scene-transformed.glb"
    ) as GLTFResult;
    return (
      <group {...props} dispose={null} ref={ref}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.TopFloor001_0.geometry}
          material={materials["Scene_-_Root"]}
          position={[-0.01, -15.098, 0]}
          rotation={[-Math.PI / 2, 0.082, -2.278]}
        />
        {props.children}
      </group>
    );
  }
);

useGLTF.preload("/models/pisa_tower/scene-transformed.glb");
