/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 -T ./scene.gltf --shadows
Author: milanpop322 (https://sketchfab.com/milanpop322)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rocky-ground-3fa6d27a59994bf0a20a4822b0b52781
Title: rocky_ground
*/

import React, { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Group } from "three";
import { GroupProps } from "@react-three/fiber";

export const RockyGround = forwardRef<Group, GroupProps>((props, ref) => {
  const { nodes, materials } = useGLTF(
    "/models/rocky_ground/scene-transformed.glb"
  ) as any;
  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_Material001_0.geometry}
        material={materials["Material.001"]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <meshStandardMaterial color={"#4384c2"} wireframe />
      </mesh>
    </group>
  );
});

useGLTF.preload("/models/rocky_ground/scene-transformed.glb");
